### ISSUE TITLE
Need to set Other Linker Flags

### ISSUE THREAD

**Issue by mfikes** [dmotz/natal#1]
Need to automate this bit:

Now, within Xcode, navigate to the _Build Settings_ for the AwesomeProject target and find _Other Linker Flags_. It should currently be set to

```
-ObjC
```

Revise this so that it is instead set to

```
${inherited}
```

Otherwise you get compilation errors like

```
/Users/mfikes/Library/Developer/Xcode/DerivedData/FutureApp-fcwewurabdzsdcblvvahdecrnxjd/Build/Products/Debug-iphonesimulator/FutureApp.app/FutureApp

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_ABYContextManager", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_ABYServer", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by dmotz** [comment]
First off, thanks for doing the hard work behind this little utility Mike.

Natal should be performing this step here: 
https://github.com/dmotz/natal/blob/master/main.coffee#L109

I've tested building and running a new app many times so I'm wondering why this step isn't happening on your end.

I take it no errors are thrown during the Natal setup? The pbxproj file is unchanged?

I'm using Xcode 6.4 on 10.10.5.

**Comment by mfikes** [comment]
Thank you as well; this looks like a great simplification in setup!

I have Xcode 6.4 on 10.10.4

Here is the transcript.

```
$ natal FutureApp
Creating FutureApp

Creating Leiningen project
Updating Leiningen project
Compiling ClojureScript
Creating React Native skeleton
Installing Pod dependencies
Updating Xcode project

When Xcode appears, click the play button to run the app on the simulator.
Then run the following for an interactive workflow:
cd future-app
./start.sh
First, choose the correct device (Probably [1]).
At the REPL prompt type this:
(in-ns 'future-app.core)
Changes you make via the REPL or by changing your .cljs files should appear live.
Try this command as an example:
(swap! app-state assoc :text "Hello Native World")

✔ Done

```

I have this in two places in `future-app/iOS/iOS/FutureApp.xcodeproj/project.pbxproj`

``` xml
                                <key>OTHER_LDFLAGS</key>
                                <string>-ObjC</string>
```

The full file for reference: https://gist.github.com/mfikes/9429415aa15e45e57129

**Comment by dmotz** [comment]
I think I figured it out.

It looks like CocoaPods prior to version 0.36 will convert the project.pbxproj file to an XML format which won't match the regular expressions Natal uses to make these updates.

When you get a chance, can you try `pod --version` to see if it's below 0.36? Does updating pod fix this?

If this is the issue, Natal could either warn about the pod version or update the XML format. The latter might be more fragile.

**Comment by mfikes** [comment]
Yes. I have Yosemite in a VM and I'll check there with 0.36 to confirm. Then if you want to add the warning, I'll leave my main machine as is to confirm your warning works and also that upgrading fixes it, if that's cool.

**Comment by dmotz** [comment]
Pushed an update that will warn about an invalid CocoaPods version.

Run `npm update -g natal` to try the latest.

**Comment by mfikes** [comment]
Cool, that warning properly detects the older version on my machine:

```
$ natal FutureApp
Creating FutureApp

Natal requires CocoaPods 0.36.4 or higher (you have 0.35.0). 
Run [sudo] gem update cocoapods and try again.
```

**Comment by mfikes** [comment]
After updating CocoaPods, confirmed things work!
