### ISSUE TITLE
Cannot start repl

### ISSUE THREAD

**Issue by podviaznikov** [dmotz/natal#11]
I think installed all dependencies and were able to see test app screen in the simulator.
However after executing "./start.sh"

I see `Searching for devices ...` and nothing else. I can select device.

Any tips how to diagnose problem? I'm on El Capitan.

**Comment by mfikes** [comment]
I'd suggest this page for helping diagnose: https://github.com/omcljs/ambly/wiki/Connectivity

**Comment by dmotz** [comment]
Try updating to Natal 0.1.0 (`npm up -g natal`) and starting a new app (`natal init YourAppName`).

**Comment by podviaznikov** [comment]
@dmotz thanks, will try!

**Comment by podviaznikov** [comment]
Using https://github.com/omcljs/ambly/wiki/Connectivity I wasn't able to identify/solve problem

**Comment by podviaznikov** [comment]
It worked @dmotz
