### ISSUE TITLE
xcodebuild fail if 8081 in use

### ISSUE THREAD

**Issue by mfikes** [dmotz/natal#14]
I'm on a Yosemite box and got this failure:

```
$ natal init FutureApp
Creating FutureApp

Creating Leiningen project
Updating Leiningen project
Compiling ClojureScript
Creating React Native skeleton
Installing Pod dependencies
Updating Xcode project
Creating Natal config
Compiling Xcode project
Command failed: xcodebuild -workspace native/ios/FutureApp.xcworkspace -scheme FutureApp -destination platform='iOS Simulator',OS=latest,id='AB511846-7E27-4434-9714-84DBCC8B5256' test
```

Digging into this, I can see that the root cause is that port 8081 is already in use on my box, which the React Native Packager wants to use.

Logging an issue in case there is anything Natal can do to soften this particular failure mode (or maybe even avoid it if React can be told to use some other port).

**Comment by dmotz** [comment]
Good catch.

For now I added a warning if 8081 is in use by anything besides the React Native packager. In the future we could add a CLI option to change the packager port.

**Comment by mfikes** [comment]
Perfect! Confirmed with master:

```
$ ./index.js init SomeAppName
Port 8081 is currently in use by another process and is needed by the React Native packager.
```
