### ISSUE TITLE
using natal with om.next

### ISSUE THREAD

**Issue by monjohn** [dmotz/natal#17]
Thanks for this great project that glues all of crazy pieces together! 

I am learning om.next and thought it would be fun to do it with React Native. I upgraded the dependency and plugged in the most basic component, but nothing is getting rendered to the screen. There are no errors in the console. It looks like om.next uses 'js/ReactDOM.render' instead of 'js/React.render'. It looks like this is because om.next uses React 0.14. If that is the case, could natal be updated as well?

**Comment by mfikes** [comment]
That's cool. David also says Om Next is no longer a "render from root" model (perhaps speaking to an optimization). Perhaps that will matter—dunno.

**Comment by dmotz** [comment]
@monjohn: @dvcrn has an Om Next implementation in progress on https://github.com/dmotz/natal/pull/18. Stay tuned.

**Comment by dmotz** [comment]
You can try the latest version of Natal with Om Next like this:

```
$ natal init TestApp --interface om-next
```
