### ISSUE TITLE
Need to bundle compiler output

### ISSUE THREAD

**Issue by mfikes** [dmotz/natal#2]
In the ClojureScript React Native Quick Start is this bit of instructions:

To bundle this output with your app, using the OS X Finder, drag the `target/out` directory into the `AwesomeProject` tree in the Xcode project navigator. You can drop it anywhere; adjacent to the existing `main.jsbundle` is fine. Make sure _Copy items if needed_ is not checked, and that _Create folder references_ is chosen.

Without doing this, Natal fails to launch the app.

**Comment by dmotz** [comment]
As with #1 I'm wondering why this step isn't happening for you in the Natal script. The relevant section is in here: https://github.com/dmotz/natal/blob/master/main.coffee#L105

Are you seeing the pbxproj file without those changes?

**Comment by mfikes** [comment]
Yeah, in hindsight this is probably a dupe of #1 in terms of root cause.

**Comment by mfikes** [comment]
Was same root cause as #1
