### ISSUE TITLE
Stuck on Searching for devices ...

### ISSUE THREAD

**Issue by zilvinasu** [dmotz/natal#21]
Initialized project using `natal init FutureApp --interface om-next`
After that I opened the created dir and tried connecting to repl using `natal repl`, but I am stack with:

```
➜  future-app  natal repl
Starting REPL

Searching for devices ...
```

Nothing seems to be happening, even after 5 minutes or so.

**Comment by mfikes** [comment]
This may be helpful: https://github.com/omcljs/ambly/wiki/Connectivity

**Comment by zilvinasu** [comment]
Forgot to mention, went through this Connectivity wiki. WebDav directory is not being mounted, tried to mount one myself using the app name, still the same problem.

The weird this is  `natal listdevices` kinda shows all the available devices, but the REPL does not seem to be able to make connection. Not sure what else I could try.

**Comment by mfikes** [comment]
Conversation with `glosoli` on IRC at http://irc.fikesfarm.com/log/clojurescript/2015-11-02.txt

**Comment by iamjarvo** [comment]
I am having this problem  with one of my laptops but not the other. I noticed that the one that works has `mDNSResponder` running

**Comment by mfikes** [comment]
Hey Jearvon,

For your laptop that’s not working, it it running OS X 10.10 less than or equal to 10.10.3?
- Mike

**Comment by zilvinasu** [comment]
Just to add more info: I have mDNSResponder running on my computer just fine.

**Comment by mfikes** [comment]
@zilvinasu Which version of Java are you using?

**Comment by zilvinasu** [comment]
@mfikes 

```
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mod
```

**Comment by mfikes** [comment]
@zilvinasu Is there any possibility of other computers on your network running 10.10–10.10.3?

**Comment by zilvinasu** [comment]
@mfikes  no

**Comment by zilvinasu** [comment]
Seems like I managed to fix my problem. It was related to my `/private/etc/hosts` having my computer name next to localhost `127.0.0.1  localhost mycomputername` removing it made everything work just fine.

**Comment by mfikes** [comment]
Interesting. Perhaps that somehow affects mDNS. Or alternatively it causes a situation Ambly is somehow mishandling it.

**Comment by mfikes** [comment]
Moved to Ambly.
