### ISSUE TITLE
rlwrap: error: Cannot execute lein: No such file or directory

### ISSUE THREAD

**Issue by gholias** [dmotz/natal#24]
I'm getting an error when trying to run the app

```
macBook-Pro-2:cat-apostrophe$ natal repl
Starting REPL
rlwrap: error: Cannot execute lein: No such file or directory
```

Any idea how can I fix that?

**Comment by dmotz** [comment]
My guess is lein isn't in your path for your non-login shell. Try adding its location to the path var in your .bashrc.

**Comment by gholias** [comment]
thanks, that was the problem
