### ISSUE TITLE
Natal app terminates if you throw an exception in the widget render function 

### ISSUE THREAD

**Issue by olivergeorge** [dmotz/natal#25]
We found that the Natal template will terminate with an error if you throw an exception when the widget render function is first run.

```
(defn widget [data owner]
  (reify
    om/IRender
    (render [this]
      (throw (js/Error "I am a render exception"))
      ...
```

It seems to be that the exception is happening before the react native exception handlers (red box) are in place.  Not sure why.  (The original problem for us was that a `println` statement in the render function throws an error for a similar reason, the `*println-fn*` wasn't set and that throws an error)

The error reported is somewhat misleading `Could not find the app init function`.  That seems to be because loading the namespace doesn't finish and the om/root call happens before the `(defn init ...)`.

The problem doesn't occur if you use .requestAnimationFrame and put om/root on the callback.

```
(.requestAnimationFrame js/window #(om/root widget app-state {:target 1}))
```

Since both the exception handler and `*print-fn*` isn't ready initially it seems like this might be a useful improvement to natal but perhaps there's a better solution.

**Comment by mfikes** [comment]
Would this `.requestAnimationFrame` call be in addition to the one in `init`?

Maybe the `om/root` call could be in `init`. (`init` could take on the meaning of “stuff to delay doing until after everything is ready”. Maybe with better semantics that that in the end and with a better name.

**Comment by anmonteiro** [comment]
as @mfikes suggested, it has to be in addition to the call already in `init`, or it doesn't reload on subsequent changes.

for the sake of completion, here's my modified `init` which seems to be working for both Om & Om Next.

#### **Om:**

``` clojure
(defn ^:export init []
  ((fn render []
     (om/root! RootComponent app-state {:target 1})
     (.requestAnimationFrame js/window render))))
```

#### **Om Next:**

``` clojure
(defn ^:export init []
  ((fn render []
     (om/add-root! reconciler RootComponent 1)
     (.requestAnimationFrame js/window render))))
```

**Comment by mfikes** [comment]
In general, subsequent exceptions can lead to a "white screen" problem, demoed here: https://youtu.be/fANy-QqGiI8

Futzing with things, just preventing things from being thrown at all by employing a `try`-`catch` could get us by for now: https://youtu.be/2DfYsgOYpW4 Maybe there's a cleaner overall solution but this at least works.

**Comment by mfikes** [comment]
Hmm... perhaps a `try`-`catch` (as illustrated in the previous comment) should be added to the `om.cljs` and `om-next.cljs` templates. (At least for now, unless someone else has found a "proper" solution?)

**Comment by anmonteiro** [comment]
:+1:

**Comment by dmotz** [comment]
I added a simple try/catch wrapper that gives some feedback to `0.1.12`. Thanks for the help in coming up with a solution. I may move this to a macro later to keep all the extra code out of the template files.

<img width="487" alt="screen shot 2015-11-23 at 11 47 45 pm" src="https://cloud.githubusercontent.com/assets/302080/11358083/e99461ce-923c-11e5-9e5f-6fc7000f3e4c.png">

**Comment by mfikes** [comment]
Yeah, you read my mind. The whole `try` could be a `try-render` macro or `with-error-view` or some suitable name.
