### ISSUE TITLE
Ignore Pods

### ISSUE THREAD

**Issue by mfikes** [dmotz/natal#44]
Add a `.gitignore` entry so that the `native/ios/Pods` directory is not included.

There is plenty of good info on whether to do this [here](https://guides.cocoapods.org/using/using-cocoapods.html#should-i-check-the-pods-directory-into-source-control).

Since `natal deps` takes care of setting up CocoaPods deps along with npm deps, there is a consistency argument that the Pods could be left out of the tree.

I tend to leave Pods out. I don't feel to strongly about the subject, but thought I'd write this ticket for consideration.

I created this sample `natal`-generated repo to illustrate that it works, and to illustrate how nice and compact the resulting committed tree is: https://github.com/mfikes/ignore-pods

You can test this repo by simply cloning it and then doing:
1. `natal deps`
2. `natal launch`

There are two .`gitignore` files that could be modified by `natal init`, one at the top and one in the `native` tree. In the sample, I modified `native/.gitignore`: https://github.com/mfikes/ignore-pods/blob/master/native/.gitignore#L36-L38

**Comment by dmotz** [comment]
Agreed
