### ISSUE TITLE
White Screen of Death

### ISSUE THREAD

**Issue by dmotz** [dmotz/natal#50]
I've been noticing this behavior often lately where a code change during a REPL session will render a white screen and all subsequent changes will be ignored. There are no errors shown in the REPL or in the error view and the only remedy is completely restarting the app / REPL session.

**Comment by dmotz** [comment]
Simple example to reproduce:

In the boilerplate template, changing this:

``` clojure
(touchable-highlight
  {:style {:backgroundColor "#999" :padding 10 :borderRadius 5}
   :onPress #(alert "HELLO!")}

  (text
    {:style {:color "white" :textAlign "center" :fontWeight "bold"}}
    "press me")))))))
```

to this:

``` clojure
(touchable-highlight
  {:style {:backgroundColor "#999" :padding 10 :borderRadius 5}
   :onPress #(alert "HELLO!")}

  #_(text
    {:style {:color "white" :textAlign "center" :fontWeight "bold"}}
    "press me")))))))
```

causes a complete breakdown with no visible errors. Undoing the change has no effect.

**Comment by hookercookerman** [comment]
I see alot of this; it does make for a painful development experience; it would be nice to debug this somehow not sure where to start? would be nice to have a catch these errors and output them so even if I do have to restart I at least know what happened.
