### ISSUE TITLE
Error near start

### ISSUE THREAD

**Issue by coyotespike** [dmotz/natal#6]
I ran 'npm install -g natal', and then 'natal FutureApp'.

I'm getting the error:

```
Creating FutureApp

undefined is not a function
```

I'm a little unsure how to begin debugging this.

**Comment by dmotz** [comment]
What version of node are you using?

**Comment by coyotespike** [comment]
Sorry, I opened this prematurely. After installing node and the react-native cli, natal is running. Thanks for your quick response though!
