### ISSUE TITLE
watchman is required

### ISSUE THREAD

**Issue by mfikes** [dmotz/natal#8]
I tried `natal FutureApp` but didn't have watchman installed at the time, and this resulted in a failure. For me it looks like the same as facebook/react-native/issues/1920

Perhaps this could be addressed by simply adding watchman (as a recommendation) to Natal's list of deps enumerated at the beginning of the Usage section of README.md. Or, maybe simply a pointer to https://facebook.github.io/react-native/docs/getting-started.html#requirements, but this seems to defeat the simplicity that Natal brings if you start having people follow manual instructions again. Hrm. Worth thinking about this one at least, IMHO.

**Comment by sgrove** [comment]
This one bit me as well, definitely hard to tell it's related to a missing
dep.
